server:
  port: 8189
  servlet:
    context-path: /market

spring:
  application:
    name: mono-market
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html